import nodemailer from 'nodemailer'
import { google } from 'googleapis'
import otpGenerator from 'otp-generator'
import crypto from 'crypto'

interface MailParams {
	userEmail: string
	name: string
}

interface VerifyOtpParams {
	otpHash: string
	email: string
	otpCode: string
}

const CLIENT_ID = process.env.CLIENT_ID as string
const CLIENT_SECRET = process.env.CLIENT_SECRET as string
const REDIRECT_URI = process.env.REDIRECT_URI as string
const REFRESH_TOKEN = process.env.REFRESH_TOKEN as string
const key = process.env.OTP_KEY as string

const oAuth2Client = new google.auth.OAuth2(CLIENT_ID, CLIENT_SECRET, REDIRECT_URI)

oAuth2Client.setCredentials({ refresh_token: REFRESH_TOKEN })
oAuth2Client.setCredentials({ refresh_token: REFRESH_TOKEN })

/*
Generates a 5 digit number (otp) and hash of (email + otp + expiry time)
*/
const otpGenerate = (email: string) => {
	const otp = otpGenerator.generate(5, {
		digits: true,
		upperCaseAlphabets: false,
		lowerCaseAlphabets: false,
		specialChars: false,
	})
	const ttl = 5 * 60 * 1000 // time to live (5 mins)
	const expires = Date.now() + ttl
	const data = `${email}.${otp}.${expires}`
	const hash = crypto.createHmac('sha256', key).update(data).digest('hex')
	const fullHash = `${hash}.${expires}`

	return [otp, fullHash]
}

/*
Sends a generated 5 digit number to email given to verify if email is valid, and
return the hash of (email + otp + expiry time) which is generated by otp_generate function
*/
const sendMail = async ({ userEmail, name }: MailParams): Promise<string | Error> => {
	try {
		const accessToken = await oAuth2Client.getAccessToken()

		const transporter = nodemailer.createTransport({
			host: 'smtp.gmail.com',
			port: 465,
			secure: true,
			auth: {
				type: 'OAuth2',
				clientId: CLIENT_ID,
				clientSecret: CLIENT_SECRET,
			},
		})

		const [otpToBeSent, hash] = otpGenerate(userEmail)

		await transporter.sendMail({
			from: 'UniPlanet ✉️ <uniplanet.info@gmail.com>',
			to: userEmail,
			subject: `Hello ${name}, Your UniPlanet Marketplace verification code`,
			text: `Hi ${name}, Please verify your email address using the following verification code: ${otpToBeSent}.
             \nThe verification code is valid for 5 minutes. Please complete the verification as soon as possible.`,
			auth: {
				user: 'uniplanet.info@gmail.com',
				refreshToken: REFRESH_TOKEN,
				accessToken: accessToken.token,
			},
		} as nodemailer.SendMailOptions)

		console.log(otpToBeSent[0])

		return hash
	} catch (error) {
		return error as string
	}
}

/*
verifies incoming request to check validity of email address
receive OTP number emailed to user, Hashed value of (user email + OTP code + expiry time)
Hashed email, otp Code and expiry date and compares with recieved Hash value to determine
validity of the user's email account
*/
const verifyOtp = async (params: VerifyOtpParams) => {
	const [otpHash, expires] = params.otpHash.split('.')
	const now = Date.now()

	// checking if OTP received is expired before continuing
	if (now > parseInt(expires, 10)) {
		const notice = 'OTP expired'
		return notice
	}

	const data = `${params.email}.${params.otpCode}.${expires}`

	const newCalculatedHash = crypto.createHmac('sha256', key).update(data).digest('hex')

	if (otpHash === newCalculatedHash) {
		return 'Success'
	}
	return 'Invalid Verfication number'
}

/*
Generates a 7 character password to be used for forgotten passwords
*/
const generatePassword = () => {
	const password = otpGenerator.generate(7, {
		digits: true,
		upperCaseAlphabets: true,
		lowerCaseAlphabets: true,
		specialChars: true,
	})
	return password
}

/*
Sends a generated 7 character password to the email address of the user using Nodemailer
*/
const sendResetPassword = async (userEmail: string): Promise<string | Error> => {
	try {
		const accessToken = await oAuth2Client.getAccessToken()

		const transporter = nodemailer.createTransport({
			host: 'smtp.gmail.com',
			port: 465,
			secure: true,
			auth: {
				type: 'OAuth2',
				clientId: CLIENT_ID,
				clientSecret: CLIENT_SECRET,
			},
		})

		const tempPassword = generatePassword()

		transporter.sendMail({
			from: 'UniPlanet ✉️ <uniplanet.info@gmail.com>',
			to: userEmail,
			subject: `Your New Password`,
			text: `
      We've received a request to reset your password for your Uniplanet Marketplace account.
      To make it easier for you, we've generated a temporary password that you can use to log in immediately.

      Temporary Password: ${tempPassword}

      Please use this temporary password to log in to your Uniplanet Marketplace account. We highly recommend changing this temporary password to your preferred one after you log in for security reasons.
      `,
			auth: {
				user: 'uniplanet.info@gmail.com',
				refreshToken: REFRESH_TOKEN,
				accessToken,
			},
		} as nodemailer.SendMailOptions)

		return tempPassword
	} catch (error) {
		return error as string
	}
}

export { sendMail, otpGenerate, verifyOtp, generatePassword, sendResetPassword }
