const nodemailer = require("nodemailer");
const { google } = require("googleapis");
const { gmail } = require("googleapis/build/src/apis/gmail");
const otpGenerator = require("otp-generator");
const crypto = require("crypto");

require("dotenv").config();

const CLIENT_ID = process.env.CLIENT_ID;
const CLIENT_SECRET = process.env.CLIENT_SECRET;
const REDIRECT_URI = process.env.REDIRECT_URI;
const REFRESH_TOKEN = process.env.REFRESH_TOKEN;
const key = process.env.OTP_KEY;

const oAuth2Client = new google.auth.OAuth2(
  CLIENT_ID,
  CLIENT_SECRET,
  REDIRECT_URI
);
oAuth2Client.setCredentials({ refresh_token: REFRESH_TOKEN });

/*
Sends a generated 5 digit number to email given to verify if email is valid, and
return the hash of (email + otp + expiry time) which is generated by otp_generate function
*/
const send_mail = async (user_email, name) => {
  try {
    const accessToken = await oAuth2Client.getAccessToken();

    let transporter = nodemailer.createTransport({
      host: "smtp.gmail.com",
      port: 465,
      secure: true,
      auth: {
        type: "OAuth2",
        clientId: CLIENT_ID,
        clientSecret: CLIENT_SECRET,
      },
    });

    const otp_to_be_sent = otp_generate(user_email);

    transporter.sendMail({
      from: "UniPlanet ✉️ <uniplanet.info@gmail.com>",
      to: user_email,
      subject: `Hello ${name}, Your UniPlanet Marketplace verification code"`,
      text: `Hi ${name}, Please verify your email address using the following verification code: ${otp_to_be_sent[0]}.
             \nThe verification code is valid for 5 minutes. Please complete the verification as soon as possible.`,
      auth: {
        user: "uniplanet.info@gmail.com",
        refreshToken: REFRESH_TOKEN,
        accessToken: accessToken,
      },
    });

    console.log(otp_to_be_sent[0]);

    return otp_to_be_sent[1];
  } catch (error) {
    return error;
  }
};

/*
Generates a 5 digit number (otp) and hash of (email + otp + expiry time)
*/
const otp_generate = (email) => {
  const otp = otpGenerator.generate(5, {
    digits: true,
    upperCaseAlphabets: false,
    lowerCaseAlphabets: false,
    specialChars: false,
  });
  const ttl = 5 * 60 * 1000; // time to live (5 mins)
  const expires = Date.now() + ttl;
  const data = `${email}.${otp}.${expires}`;
  const hash = crypto.createHmac("sha256", key).update(data).digest("hex");
  const full_hash = `${hash}.${expires}`;

  return [otp, full_hash];
};

/*
verifies incoming request to check validity of email address
receive OTP number emailed to user, Hashed value of (user email + OTP code + expiry time)
Hashed email, otp Code and expiry date and compares with recieved Hash value to determine
validity of the user's email account
*/
const verfy_otp = async (params) => {
  let [otpHash, expires] = params.otpHash.split(".");
  let now = Date.now();

  // checking if OTP received is expired before continuing
  if (now > parseInt(expires)) {
    return "OTP expired";
  }

  let data = `${params.email}.${params.otpCode}.${expires}`;

  let newCalculatedHash = crypto
    .createHmac("sha256", key)
    .update(data)
    .digest("hex");

  if (otpHash === newCalculatedHash) {
    return "Success";
  }
  return "Invalid Verfication number";
};

/*
Generates a 7 character password to be used for forgotten passwords
*/
const generate_password = () => {
  const password = otpGenerator.generate(7, {
    digits: true,
    upperCaseAlphabets: true,
    lowerCaseAlphabets: true,
    specialChars: true,
  });
  return password;
};

/*
Sends a generated 7 character password to the email address of the user using Nodemailer
*/
const send_reset_password = async (user_email) => {
  try {
    const accessToken = await oAuth2Client.getAccessToken();

    let transporter = nodemailer.createTransport({
      host: "smtp.gmail.com",
      port: 465,
      secure: true,
      auth: {
        type: "OAuth2",
        clientId: CLIENT_ID,
        clientSecret: CLIENT_SECRET,
      },
    });

    const temp_password = generate_password();

    transporter.sendMail({
      from: "UniPlanet ✉️ <uniplanet.info@gmail.com>",
      to: user_email,
      subject: `Your New Password`,
      text: `
      We've received a request to reset your password for your Uniplanet Marketplace account.
      To make it easier for you, we've generated a temporary password that you can use to log in immediately.

      Temporary Password: ${temp_password}

      Please use this temporary password to log in to your Uniplanet Marketplace account. We highly recommend changing this temporary password to your preferred one after you log in for security reasons.
      `,
      auth: {
        user: "uniplanet.info@gmail.com",
        refreshToken: REFRESH_TOKEN,
        accessToken: accessToken,
      },
    });

    return temp_password;
  } catch (error) {
    return error;
  }
};

module.exports = {
  send_mail,
  verfy_otp,
  otp_generate,
  generate_password,
  send_reset_password,
};
