// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDnfaEQyYw_54serI8H9jphtGKQqmQAwU',
    appId: '1:1003008222202:web:59e470045d22d8f3517a43',
    messagingSenderId: '1003008222202',
    projectId: 'pushnotification-uniplanet',
    authDomain: 'pushnotification-uniplanet.firebaseapp.com',
    storageBucket: 'pushnotification-uniplanet.appspot.com',
    measurementId: 'G-D2QQBBFX3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw2Vy6fUh35DUppMs8jJXgSuRzA5Jz9NE',
    appId: '1:1003008222202:android:0ef2d8ce865f9a7c517a43',
    messagingSenderId: '1003008222202',
    projectId: 'pushnotification-uniplanet',
    storageBucket: 'pushnotification-uniplanet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_CUkH5w9cTWWnt4IWwqKhSeDeUIAUniw',
    appId: '1:1003008222202:ios:784c18124b74d35a517a43',
    messagingSenderId: '1003008222202',
    projectId: 'pushnotification-uniplanet',
    storageBucket: 'pushnotification-uniplanet.appspot.com',
    iosBundleId: 'shop.uniplanet.uniket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_CUkH5w9cTWWnt4IWwqKhSeDeUIAUniw',
    appId: '1:1003008222202:ios:784c18124b74d35a517a43',
    messagingSenderId: '1003008222202',
    projectId: 'pushnotification-uniplanet',
    storageBucket: 'pushnotification-uniplanet.appspot.com',
    iosBundleId: 'shop.uniplanet.uniket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDnfaEQyYw_54serI8H9jphtGKQqmQAwU',
    appId: '1:1003008222202:web:dc5b5a69e652573d517a43',
    messagingSenderId: '1003008222202',
    projectId: 'pushnotification-uniplanet',
    authDomain: 'pushnotification-uniplanet.firebaseapp.com',
    storageBucket: 'pushnotification-uniplanet.appspot.com',
    measurementId: 'G-PY9F8JG34T',
  );

}