// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDnfaEQyYw_54serI8H9jphtGKQqmQAwU',
    appId: '1:1003008222202:web:819c4e3b262087ba517a43',
    messagingSenderId: '1003008222202',
    projectId: 'pushnotification-uniplanet',
    authDomain: 'pushnotification-uniplanet.firebaseapp.com',
    storageBucket: 'pushnotification-uniplanet.appspot.com',
    measurementId: 'G-CRF5YRLGL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw2Vy6fUh35DUppMs8jJXgSuRzA5Jz9NE',
    appId: '1:1003008222202:android:a5a7c8d2c98f34e1517a43',
    messagingSenderId: '1003008222202',
    projectId: 'pushnotification-uniplanet',
    storageBucket: 'pushnotification-uniplanet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_CUkH5w9cTWWnt4IWwqKhSeDeUIAUniw',
    appId: '1:1003008222202:ios:8e61900be8bfcf9a517a43',
    messagingSenderId: '1003008222202',
    projectId: 'pushnotification-uniplanet',
    storageBucket: 'pushnotification-uniplanet.appspot.com',
    iosBundleId: 'shop.uniplanet.uniplanet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_CUkH5w9cTWWnt4IWwqKhSeDeUIAUniw',
    appId: '1:1003008222202:ios:a8f48b7b04e769a5517a43',
    messagingSenderId: '1003008222202',
    projectId: 'pushnotification-uniplanet',
    storageBucket: 'pushnotification-uniplanet.appspot.com',
    iosBundleId: 'shop.uniplanet.uniplanet.RunnerTests',
  );
}
